routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $message = '';
    return view('welcome',compact('message'));
//    return redirect()->route('login');
})->name('main');

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });

    Route::resource('clients',\App\Http\Controllers\ClientController::class);


});


//Auth::routes([
//    'register' => false, // Registration Routes...
//    'reset' => false, // Password Reset Routes...
//    'verify' => false, // Email Verification Routes...
//]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('expire',function (\Illuminate\Http\Request $request){
    try {
        $request->validate([
            'url'=>'required'
        ]);

        $client = \App\Models\Client::where('url','=',$request->url)->first();
        if ($client){
            return response()->json([
                'status'=>true,
                'data'=>$client->date,
                'limit'=>$client->limit,
                'message'=>'Active'
            ]);
        }else{
            return response()->json([
                'status'=>false,
                'data'=>'2020-01-01',
                'limit'=> 0,
                'message'=>'Topilmadi'
            ]);
        }

    }catch (\Exception $exception){
        return response()->json([
            'status'=>false,
            'data'=>'2020-01-01',
            'limit'=> 0,
            'message'=>'Topilmadi'
        ]);
    }
});

Route::post('message', function (\Illuminate\Http\Request $request){

    \Illuminate\Support\Facades\Http::post('https://api.telegram.org/bot6144318751:AAFIKgtEPZK59Q61Pt0V9eQY-rUf-6wzgyQ/sendMessage', [
        'chat_id'=>531110501,
//        'chat_id'=>507405877,
        'text'=>'Name: '.$request->name.', '.
            ' Phone: '.$request->phone. ', '.
            ' Center: '.$request->center. ', '.
            ' Comment: '.$request->comment,
        'parse_mode'=>'html'
    ]);

    return redirect()->back()->with([
        'message'=>'Ariza yuborildi, Tez orada aloqaga chiqamiz.'
    ]);


})->name('message');

resources/views/admin/edit.blade.php
@extends('layouts.main')
@section('main-content')
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Admin edit</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('admin.update', Auth::user()->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input name="name" type="text" class="form-control" value="{{ $admin->name }}" id="exampleInputEmail1" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input name="email" type="email" class="form-control" value="{{ $admin->email }}" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input name="password" type="text" class="form-control" id="exampleInputPassword1" placeholder="New Password" required>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="exampleInputFile">File image</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input name="image" id="imgInp" onchange="preview(frame)" type="file" class="custom-file-input" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <label class="mb-2" for="rasm"><b>Here image</b></label>
                        <img id="frame" class="ml-2" src="{{asset('public/storage/images/'.$admin->image)}}" width="100px" height="100px" alt="Rasm"/>
                    </div>
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <!-- /.card -->
@endsection